import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/NavBar/Nav";
import Footer from "@/components/footer/Footer";
import ImportBsJS from "@/app/importBsJS";

import 'bootstrap/dist/css/bootstrap.min.css';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "The Riders",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ImportBsJS />
        <Nav/>
        {children}
        <Footer/>
        <ToastContainer />
      </body>
    </html>
  );
}
